### ISSUE TITLE
disabled the plugin by mistake and enabled again but nothing pops up in my suggestions anymore, uninstalled and installed again also. No luck 

### ISSUE THREAD

**Issue by ravi-python-mss** [jundat95/react-native-snippet#19]

**Comment by dylanngo95** [comment]
Thank you for your report

**Comment by dylanngo95** [comment]
Hi @ravi-python-mss Can you give me the Opera System version, and Visual Studio Code version.
Thanks.

**Comment by ravi-python-mss** [comment]
![image](https://user-images.githubusercontent.com/73024479/102959794-77fb2480-4506-11eb-96dc-3a435c9ed3e4.png)

**Comment by ravi-python-mss** [comment]
@dylanngo95 check this out, also I don't understand what you mean by opera version. I am using Ubuntu 17 on my system.

**Comment by dylanngo95** [comment]
Hi, @ravi-python-mss make sure this snippet in a javascript file. It's mean you should use the snippet in a file like index.js

**Comment by ravi-python-mss** [comment]
@dylanngo95 no it's not there, can you tell me what to write there?
