### ISSUE TITLE
Component.PropTypes should be a lowercase p for prop

### ISSUE THREAD

**Issue by daraclare** [jundat95/react-native-snippet#5]
I'm getting a console error for the component PropTypes snippet, I think 

`pt→ | Component.PropTypes = {};`
 
should be 

`pt→ | Component.propTypes = {};`

with propTypes spelt with a lowercase 'p' 

Thanks!

**Comment by daraclare** [comment]
PR created: https://github.com/jundat95/react-native-snippet/pull/6

**Comment by jundat95** [comment]
thank you !!
